config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users, :only => [:edit, :update, :show]
  
  resource :myposts
  
  resource :dashboards

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  
  resources :posts do

  	# user do
  	# 	get :dashboard
  	# end 

	collection do
		get :latest
	end

	resources :comments do

		collection do
			get :latest
		end

	end

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
	has_many :posts_cats
	has_many :posts, :through => :posts_cats

end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :post
	belongs_to :user

end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord

	has_many :comments

	has_many :posts_cats
	has_many :cats, :through => :posts_cats

	belongs_to :user
	
end

app/models/posts_cat.rb
class PostsCat < ApplicationRecord
	belongs_to :post
	belongs_to :cat
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :set_post

	def index
		@comments=Comment.all
	end 

	def create
		@comment=@post.comments.build(comment_params)
		@comment.user=current_user
		if @comment.save
			@post.comment_time=@comment.created_at
			@post.save
			redirect_to post_path(@post)
		else 
			redirect_to post_path(@post)
		end
	end

	def destroy
		@comment=@post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end

	protected 

	def set_post
	 	@post = Post.find(params[:post_id])
	end


	def comment_params
		params.require(:comment).permit(:body, :user_id)
	end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

	def show
		@usercount=User.count(:all)
		@postcount=Post.count(:all)
		@commentcount=Comment.count(:all)
	end

end

app/controllers/myposts_controller.rb
class MypostsController < ApplicationController

	def show
		@posts=current_user.posts
		@comments=current_user.comments
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!

	def index

		if params[:cat]
			@category = Cat.find_by_name(params[:cat])
			@posts = @category.posts
		else
			@posts = Post.all
		end

		if params[:order]
			sort_by = "#{params[:order]}"
		else
			sort_by = "created_at"	
		end

		@posts=@posts.order("#{sort_by} DESC")

		@posts=@posts.page(params[:page]).per(5)

	end

	def show
		@post=Post.find(params[:id])
		@comment=Comment.new
		@comments=@post.comments
		@cat=Cat.new
		@cats=Cat.all
	end 

	def new
		@post=Post.new
	end

	def create
		@post=Post.new(post_params)
		@post.user=current_user
		if @post.save
			flash[:notice]="Post was successfully created"
			redirect_to posts_path
		else 
			flash[:notice]="Post was not saved. Please retry."
			render :action => :new
		end
	end

	def edit 
		@post=Post.find(params[:id])
	end

	def update
		@post=Post.find(params[:id])
		if @post.update(post_params)
			flash[:notice]="Post was successfully updated"
			redirect_to posts_path
		else 
			flash[:notice]="Post was not saved. Please retry."
			render :action => :new	
		end
	end

	def destroy
		@post=Post.find(params[:id])
		@post.destroy
		redirect_to(posts_path)
	end

	protected 

	def post_params
		params.require(:post).permit(:title, :body, :comment_id, :cat_ids, :user_id => [])
	end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
	end

	def edit 
		@user=User.find(params[:id])
	end

	def update
		@user=User.find(params[:id])
		if @user.update(user_params)
			flash[:notice]="Profile was successfully updated"
			redirect_to posts_path
		else 
			flash[:notice]="Updates were not saved. Please retry."
			render :action => :new
		end	
	end

	protected 

	def user_params
		params.require(:user).permit(:name, :aboutyou, :birthday)
	end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/myposts_helper.rb
module MypostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboards/show.html.erb
<h1>Dashboard</h1>

<p> Number of users: <%= @usercount %> </p>

<p> Number of posts: <%= @postcount %> </p>

<p> Number of comments: <%= @commentcount %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Site3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p style="color: green"><%= flash[:notice] %></p>
    
    <%= yield %>

  </body>
</html>

app/views/myposts/show.html.erb
<h4> My posts </h4>

<% @posts.each do |p| %>
	<%=p.id %>
	<%=p.title %>
	<%=p.created_at %>
	<%=p.body %>
	</p>
	<p></p>	
<% end %>


<h4> My comments </h4>

<% @comments.each do |p| %>
	<i><%= p.body %></i>
	<%= p.created_at %>
	<%= link_to p.post.title, post_path(p.post) %>
	</p>
	<p></p>	
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>

	<div class="field">
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>

	<div class="field">
		<%= f.label :body %>
		<%= f.text_area :body %>
	</div>

	<div>
		<%= f.submit %>
	</div>

	<%= f.collection_check_boxes(:cat_ids, Cat.all, :id, :name) %>

<% end %>

app/views/posts/comments.html.erb
<h2>Recently commented</h2>

<% @latest_posts.each do |p| %>
	<%=p.id %>
	<%=p.title %>
	<%=p.created_at %>
	<p></p>	
<% end %>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h2> Welcome to this Social Networking Website </h2>

<h4> My Account </h4>

<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <p><%= link_to 'Edit login details', edit_user_registration_path, :class => 'navbar-link' %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></p>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<p></p>

<%= link_to 'Your Posts', myposts_path %>

<h4> About this site </h4>

<%= link_to 'Dashboard', dashboards_path %>

<p></p>

<h4> All posts </h4>

<% @posts.each do |p| %>
	<%=p.id %>
	<%=p.title %>
	<%=p.created_at %>
	<%=link_to "Show", post_path(p) %>
	<%=link_to "Edit", edit_post_path(p) if current_user==p.user %>
	<%=link_to_if((current_user==p.user), "Delete", post_path(p), :method=>:delete) {""}%>

	</p>
	<p></p>	
<% end %>

<p></p>

<%= paginate @posts %>

<p> Sort by:  
<%= link_to 'Title', posts_path(:order => "title") %>
<%= link_to 'Recently commented', posts_path(:order => "comment_time") %>
<%= link_to 'Recently created', posts_path(:order => "created_at") %></p>

<p> Filter posts by category: </p>

<% Cat.all.each do |c| %>
	<%= link_to c.name, posts_path(:cat=>c.name) %>
<% end %>

<h4> Create new post </h4>
<p><%= link_to "New post", new_post_path %></p>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p>
	<%= @post.body %>
</p>

<h4> =====categories==== </h4>

<% @post.cats.each do |g| %>
	<%= g.name %>
<% end %>

<h4> =====comments==== </h4>

<% @comments.each_with_index do |p, i| %>
	<%= i + 1 %>
	<%= p.body %>
	<%= p.created_at %>
	<p></p>
	<%=link_to_if((current_user==p.user), "Delete", post_comment_path(@post, p), :method=>:delete) {""}%>
<% end %>


<%= form_for @comment, :url => post_comments_path(@post) do |f| %>

	<div class="field">
		<%= f.text_area :body %>
	</div>

	<div>
		<%= f.submit %>
	</div>

<% end %>

app/views/user/_form.html.erb
<%= form_for(@user) do |f| %>

	<div class="field">
		Your Name:
		<%= f.text_area:name %>
	</div>

	<div class="field">
		About You:
		<%= f.text_area :aboutyou %>
	</div>

	<div class="field">
		Your Birthday:
		<%= f.text_area :birthday %>
	</div>

	<div>
		<%= f.submit %>
	</div>

<% end %>

app/views/user/edit.html.erb
<%= render 'form', user: @user %>

app/views/user/new.html.erb
<%= render 'form', user: @user %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

	<div class="field">
		Your Name:
		<%= f.text_area:name %>
	</div>

	<div class="field">
		About You:
		<%= f.text_area :aboutyou %>
	</div>

	<div class="field">
		Your Birthday:
		<%= f.text_area :birthday %>
	</div>

	<div>
		<%= f.submit %>
	</div>

<% end %>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>